### ISSUE TITLE
Does this implement both client and server in Rust?

### ISSUE THREAD

**Issue by TCROC** [szarykott/signalrs#1]

**Comment by szarykott** [comment]
Welcome!

Initial plan was to support only server, but it seems that to reach at least minimal feature parity with .NET I also need to support client, which I am working on now.

There is much more work than I anticipated initially, but I am progressing on and off. no ETA yet, though. However, I plan to release as soon as I have workinng server and client. 

The way it is now, server works, it communnicates with JS scripts in browser or .NET implementation, but I am not sure how well it works. Client's development is on early stage (internals are quasi-ready), it still needs some time to reach usable state,

**Comment by TCROC** [comment]
> Welcome!
> 
> Initial plan was to support only server, but it seems that to reach at least minimal feature parity with .NET I also need to support client, which I am working on now.
> 
> There is much more work than I anticipated initially, but I am progressing on and off. no ETA yet, though. However, I plan to release as soon as I have workinng server and client.
> 
> The way it is now, server works, it communnicates with JS scripts in browser or .NET implementation, but I am not sure how well it works. Client's development is on early stage (internals are quasi-ready), it still needs some time to reach usable state,

Thanks for the update!  I look forward to trying it out in the future!  Should we leave this open until client is ready or close it now since question is answered?

**Comment by szarykott** [comment]
Actually, I had a change of plans and the client is ready and published to [crates.io](https://crates.io/crates/signalrs-client). I'd appreciate it if you tested it and opened new issues about bugs and missing features/documentation.

Please mind that this is quite an early stage and there are some things that are either unsupported (for instance MessagePack, LongPolling, stream arguments to client-side hubs) or simply require some more care to work in all circumstances. But a solid portion of functionalities is supported, the ones I deemed most useful.

You'll find examples for various use cases in signalrs-client/examples in this repository and also in docs.rs documentation.

If this is ok for you, please close the issue :)

**Comment by TCROC** [comment]
Yep this is okay with me! I'll close it :) 

Thanks again!
