### ISSUE TITLE
native-tls

### ISSUE THREAD

**Issue by devalain** [szarykott/signalrs#3]
Hello, thank you for sharing these crates !

I have a feature request for the `signalrs-client` crate: 

Could you add optional features that opt in the `native-tls` or `rustls-tls-native-roots` features of the `tokio-tungstenite` crate ?

It would be great !

**Comment by xamgore** [comment]
So, the fix is just a matter of proxying dependencies 👍 

https://github.com/snapview/tokio-tungstenite/issues/93#issuecomment-603600819
